# Generated by Django 4.2.10 on 2024-02-22 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('artigo', models.TextField(max_length=1000)),
                ('categoria', models.CharField(choices=[('INFORMATIVO', 'iNFORMATIVO'), ('NOTICIA', 'Notícia'), ('CONTO', 'Conto'), ('OUTROS', 'Outros')], max_length=15)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
