# Generated by Django 4.2.10 on 2024-02-28 18:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nic', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=15)),
                ('descricao', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('Securant', 'Securant'), ('LGPD', 'LGPD')], max_length=15)),
                ('descricao', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nic', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=1000)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processo', to='grc.dimension')),
            ],
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nic', models.CharField(max_length=10)),
                ('descricao', models.TextField(max_length=1000)),
                ('atendida', models.CharField(choices=[('SIM', 'Sim'), ('EmP', 'Em parte'), ('NAO', 'Não')], max_length=15)),
                ('data_conclusao', models.DateTimeField(default=django.utils.timezone.now)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimento', to='grc.processo')),
            ],
        ),
        migrations.AddField(
            model_name='dimension',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension', to='grc.framework'),
        ),
    ]
