# Generated by Django 4.2.10 on 2024-03-13 17:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=1000)),
                ('responsavel', models.TextField(max_length=100)),
                ('concluido', models.CharField(choices=[('ANDAMENTO', 'Andamento'), ('CONCLUIDO', 'Concluido'), ('CANCELADO', 'Cancelado')], max_length=15)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('data_planejada', models.DateField(default=None)),
                ('data_conclusao', models.DateField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='data_conclusao',
            field=models.DateField(default=None),
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=1000)),
                ('responsavel', models.TextField(max_length=100)),
                ('concluida', models.CharField(choices=[('SIM', 'Sim'), ('EmP', 'Em parte'), ('NAO', 'Não')], max_length=15)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('data_planejada', models.DateField(default=None)),
                ('data_conclusao', models.DateField(default=None)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefa', to='grc.plano')),
            ],
        ),
        migrations.AddField(
            model_name='plano',
            name='procedimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano', to='grc.procedimento'),
        ),
    ]
