# Generated by Django 4.2.10 on 2024-03-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0002_plano_alter_procedimento_data_conclusao_tarefa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='responsavel',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='responsavel',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
