# Generated by Django 4.2.10 on 2024-03-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0003_alter_plano_responsavel_alter_tarefa_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='responsavel',
        ),
    ]
