# Generated by Django 4.2.10 on 2024-03-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0004_remove_plano_responsavel_remove_tarefa_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='responsavel',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='responsavel',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
