# Generated by Django 4.2.10 on 2024-03-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0005_plano_responsavel_tarefa_responsavel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plano',
            old_name='concluido',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='tarefa',
            old_name='concluida',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='plano',
            name='responsavel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='responsavel',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
