# Generated by Django 4.2.10 on 2024-04-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0006_rename_concluido_plano_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='status',
            field=models.CharField(choices=[('PLANEJADO', 'Planejado'), ('ANDAMENTO', 'Andamento'), ('CONCLUIDO', 'Concluido'), ('CANCELADO', 'Cancelado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('PLANEJADO', 'Planejado'), ('ANDAMENTO', 'Andamento'), ('CONCLUIDO', 'Concluido'), ('CANCELADO', 'Cancelado')], max_length=15),
        ),
    ]
